# Change these first
owner: ASDev-Official # Your GitHub organization or username, where this repository lives
repo: weatherfast-status-monitor # The name of this repository

sites:
  - name: Web App
    url: https://app.weatherfast.aadish.dev
    
  - name: API - Notifications
    url: https://api.weatherfast.aadish.dev
    
  - name: "API - SG - Two Hour Forecast"
    url: "https://api.weatherfast.aadish.dev/api/sg/two-hour-forecast"

  - name: "API - SG - Twenty Four Hr Forecast"
    url: "https://api.weatherfast.aadish.dev/api/sg/twenty-four-hr-forecast"
  
  - name: "API - SG - Four Day Forecast"
    url: "https://api.weatherfast.aadish.dev/api/sg/four-day-forecast"
  
  - name: "API - SG - Air Temperature"
    url: "https://api.weatherfast.aadish.dev/api/sg/air-temperature"
  
  - name: "API - SG - Rainfall"
    url: "https://api.weatherfast.aadish.dev/api/sg/rainfall"
  
  - name: "API - SG - Relative Humidity"
    url: "https://api.weatherfast.aadish.dev/api/sg/relative-humidity"
  
  - name: "API - SG - Wind Speed"
    url: "https://api.weatherfast.aadish.dev/api/sg/wind-speed"
  
  - name: "API - SG - Psi"
    url: "https://api.weatherfast.aadish.dev/api/sg/psi"
  
  - name: "API - SG - Flood Alerts"
    url: "https://api.weatherfast.aadish.dev/api/sg/flood-alerts"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: weatherfast-status.aadish.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/ASDev-Official/weatherfast/refs/heads/main/web/android-chrome-512x512.png
  favicon: https://raw.githubusercontent.com/ASDev-Official/weatherfast/refs/heads/main/web/favicon.ico
  theme: "ocean"
  name: "WeatherFast Status"
  introTitle: ""
  introMessage: ""

i18n:
  footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
